### ISSUE TITLE
Hanging threads preventing app exiting with monix TaskApp

### ISSUE THREAD

**Issue by samzx** [softwaremill/sttp#519] opened 2020-04-30 01:54 UTC
Hello,

It seems that when using `TaskApp` from Monix when I return `ExitCode.Success` after a request and closing the backend (using Resource), the app hangs and doesn't exit. Looks like there's a thread hanging that's preventing the app from exiting.

Returning `ExitCode.Error` allows the app to exit though.

Can someone take a look please? :)

Here's an example project that exhibits this behaviour.
https://github.com/samzx/sttp-hanging-thread

Example code:
```
import cats.effect.{ExitCode, Resource}
import monix.eval.{Task, TaskApp}
import sttp.client.asynchttpclient.monix.AsyncHttpClientMonixBackend
import sttp.client.{quickRequest, _}

object Main extends TaskApp {
  def run(args: List[String]): Task[ExitCode] = {
    Resource
      .make(AsyncHttpClientMonixBackend())(backend => Task(backend.close()))
      .use { implicit backend =>
        val request = quickRequest.get(uri"https://postman-echo.com/get?foo=bar")
        request.send().map { response =>
          println(response.body)
          ExitCode.Success
        }
      }
  }
}
```

**Comment by adamw** [comment] 2020-04-30 07:37
The problem is here: `Task(backend.close())`. The `close()` method itself returns a `Task`, so you are creating a `Task` which computes another `Task` - but never runs it. So the closing never happens. You can fix this by doing: 

```
 Resource
      .make(AsyncHttpClientMonixBackend())(_.close())
```

Or simply using `AsyncHttpClientMonixBackend.resource()` :)

**Closed by adamw** 2020-04-30 07:37 UTC

**Comment by samzx** [comment] 2020-04-30 23:56
@adamw Wow thanks heaps! 🙂
