### ISSUE TITLE
Alot of "Parsing failure: exhausted input" after switching to ZIO 2.0 and using HttpClientZioBackend

### ISSUE THREAD

**Issue by peterstorm** [softwaremill/sttp#1610] opened 2022-11-03 08:39 UTC
Hello!

We just made the switch to ZIO 2.0, and using `HttpClientZioBackend` we are getting a lot of errors.
I have talked to people in the zio discord, and a few people are experiencing the same.

Also they said (we have not tried this, as it's a huge code change), switching to a different backend alleviates the problem.

I'm sorry I cannot provide a reproducible example :(

sttp version: 3.8.3

**Comment by Pask423** [comment] 2022-11-03 08:58
@peterstorm you are using normal endpoints, websockets, streaming ?

**Comment by peterstorm** [comment] 2022-11-03 09:14
We do everything, as far as I know, this is our type: type `SttpClient = SttpBackend[Task, ZioStreams with WebSockets]`

**Comment by Pask423** [comment] 2022-11-04 00:11
I mentioned you on gitter in some old issue which may be similar to your. Could you provide a stack trace or some part of stack trace or any other more specific information when this error occurs ?

**Comment by vmandrychenko** [comment] 2022-11-10 19:17
Confirmed today, after an update from STTP 2 to STTP 3 on Sep 28th at random 1 in every 10k-100k responses from the server was cut off and circe was failing to parse json that is incomplete. We retry on error and subsequently it succeeds. Our backend logs show the whole request was sent over the pipe.

I am investigating further.



Verisons:
async-http-client-backend-zio_2.13:3.8.2
client3:core_2.13:3.8.2
client3:circe_2.13:3.8.2
client3:zio_2.13:3.8.2

We use: AsyncHttpClientZioBackend()

**Comment by vmandrychenko** [comment] 2022-11-10 23:28
Update: trying ArmeriaZioBackend(), so far so good. Given the issue is hard to reproduce, we will wait before declaring that the issue is with Java 11 HttpClient based zio backend.

**Comment by peterstorm** [comment] 2022-11-11 10:36
> Update: trying ArmeriaZioBackend(), so far so good. Given the issue is hard to reproduce, we will wait before declaring that the issue is with Java 11 HttpClient based zio backend.

Just an update from us as well.

We tried to wrap the deprecated `AsyncHttpClientZioBackend()` in `scoped` and it seems to have elided the `exhausted input` errors.

**Comment by vmandrychenko** [comment] 2022-12-08 19:43
> Confirmed today, after an update from STTP 2 to STTP 3 + Zio 1 to Zio 2 on Sep 28th at random 1 in every 10k-100k responses from the server was cut off and circe was failing to parse json that is incomplete (HTTP 200 - OK). We retry on error and subsequently it succeeds. Our backend logs show the whole request was sent over the pipe and HTTP status is 200.
> 
> I am investigating further.
> 
> Verisons: async-http-client-backend-zio_2.13:3.8.2 client3:core_2.13:3.8.2 client3:circe_2.13:3.8.2 client3:zio_2.13:3.8.2
> 
> We use: AsyncHttpClientZioBackend() (I am aware that it is deprecated, switching to HttpClientZioBackend resulted in other issues (have to investigate deeper to provide a conclusion), so we reverted).

Here is another update from us on the issue. 

As we started experimenting, we discovered that we were creating a new client instance for every request and closed it after request processing finished. This creation of many instances greatly increased the chance of the problem occurring. Once we started reusing the client, we only encountered the issue once in the last 30 days and consider it solved. 

Using ArmeriaHttpBackend also reduced the problem occurrence but didn't eliminate it, although initial results looked promising.

**Comment by adamw** [comment] 2022-12-09 14:39
@vmandrychenko Thanks for the update. Can we consider this issue closed? I don't think there's something that we can fix on the sttp side. Occasional "exhausted input" exceptions might occur when the http connection breaks, e.g. on the client side.

**Closed** 2022-12-10 10:14 UTC

**Comment by guersam** [comment] 2023-03-02 17:07
Maybe related to this one? https://github.com/zio/interop-reactive-streams/pull/339

**Comment by guersam** [comment] 2023-03-06 06:54
FYI: I was able to reproduce this issue under 100 req/sec with both `HttpClientZioBackend` and `AsyncHttpClientZioBackend`. After bumping zio-interop-reactive-streams from 2.0.0 to 2.0.1 which contains [the patch](https://github.com/zio/interop-reactive-streams/pull/339), it's completely gone.

As sttp v3.8.12 updated zio-interop-reactive-streams, I think it's solved now.

**Comment by JonNorman** [comment] 2023-03-27 10:28
Can confirm that we updated from 3.8.3 to 3.8.13 (sttp core and circe) and 2.0.1 to 2.0.10 (zio core) in our service and saw the "exhausted input" errors entirely disappear.

Thanks for the continued work and improvements!

**Comment by Ivoyaa** [comment] 2023-09-07 07:42
> Can confirm that we updated from 3.8.3 to 3.8.13 (sttp core and circe) and 2.0.1 to 2.0.10 (zio core) in our service and saw the "exhausted input" errors entirely disappear.
> 
> Thanks for the continued work and improvements!

Also worked for us!
