### ISSUE TITLE
Class cast errors when using zio streaming backend

### ISSUE THREAD

**Issue by nickrobison** [softwaremill/sttp#1115] opened 2021-09-22 19:10 UTC
Hi folks, I had a quick question regarding the streaming functionality of the Zio backend:
I have the following code that I'm attempting to use to return the http response stream to the caller:

```
basicRequest
          .method(Method(proxyRequest.method.value), uri)
          .headers(proxyRequest.headers.map(h => Header(h.name(), h.value())): _*)
          .streamBody(ZioStreams)(entityStream)
          .response(asStreamUnsafe(ZioStreams))
```

The response type is `Request[Either[String, BinaryStream]`; however, when I attempt to run the code, I get the following error:
```
class zio.stream.ZStream$$anon$1 cannot be cast to class scala.util.Either
```
The caller looks like this: `client.send(req).map(_.body)`
I'm sure there are a couple of things that I'm doing wrong, but I'm stumped as to why the types don't seem to line up with the actual implementation.

**Comment by adamw** [comment] 2021-09-23 15:03
Could you post a full reproducing example? Which backend are you using?

So far, works for me :)

```scala
import sttp.capabilities.zio.ZioStreams
import sttp.client3._
import sttp.client3.asynchttpclient.zio.{AsyncHttpClientZioBackend, SttpClient, send}
import zio._
import zio.console._
import zio.stream._

object Test extends App {
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] = send(
    basicRequest
      .post(uri"https://httpbin.org/post")
      .streamBody(ZioStreams)(Stream.fromIterable("abc".getBytes))
      .response(asStreamUnsafe(ZioStreams))
  )
    .flatMap(response => putStrLn(s"RECEIVED:\n${response.body}"))
    .provideCustomLayer(AsyncHttpClientZioBackend.layer())
    .exitCode
}
````

**Comment by adamw** [comment] 2022-03-02 20:36
Closing due to lack of reproducing example

**Closed by adamw** 2022-03-02 20:36 UTC
Labels: possible bug
