### ISSUE TITLE
[BUG]  BasicRequest.response(asJsonEither[SomeTraitError, SomeResponse]) asJsonEither serialization issue

### ISSUE THREAD

**Issue by Allocer** [softwaremill/sttp#1770] opened 2023-03-16 09:55 UTC
Tapir version: 1.2.10

Scala version: 2.13.10

What is the problem?

I have an issue with serialization through `asJsonEither ` in `BasicRequest` sttp client. It seems the response from given server is never map correctly to trait given in `asJsonEither[SomeTraitError, SomeResponse]`.

Let me show how te structure looks like.

I have errors structure like this:

```
sealed trait GeneralError extends Throwable {
  def message: String
  def code: Int
}

object Errors {

  final case class FirstErrorImpl(detail: String,  code: Int) extends GeneralError {
    override def getMessage: String = ...
  }

 final case class SecondErrorImpl(detail: String,  code: Int) extends GeneralError {
    override def getMessage: String = ...
  }
}
```

Now, I want to map errors from client to one of them, so when I created `BasicRequest` I put `GeneralError ` as a type:
```
      basicRequest
        .get(...)
        .response(asJsonEither[GeneralError , SomeResponse])
        .send(backend)
        .map(_.body.left.map {
          case HttpError(body, statusCode) => mapErrorToImpl(statusCode, body)
          case DeserializationException(_, _) => SomeSerializationError()
        })
        .flatMap(ZIO.fromEither(_))

```
Then, I want to map error to concrete error implementation showed above.
But, when I ran this code I ALWAYS get a DeserializationError
![image](https://user-images.githubusercontent.com/3626892/225579536-d2a0676b-94ec-404b-b55e-14419ef84b0c.png)

It never enters first case `HttpError(... ,...)`, it always returns `DeserializationError`.

When I change this fragment:
`.response(asJsonEither[GeneralError , SomeResponse])`

to:
`.response(asJsonEither[FirstErrorImpl, SomeResponse])`

It works correctly. Enters first ` case HttpError(body, statusCode)`, map error in a good way and there is no `DeserializationException`. The problem is only with traits.

Maybe there is a some strange mistake on my side, but in my opinion there is a bug with `asJsonEither` method, so I decided to raise it here.
Can you help me with it?

**Comment by adamw** [comment] 2023-03-16 11:58
moving to sttp, sorry, I pasted in the wrong repository :)

maye you can also add some simple definitions for the `FirstErrorImpl`? So that we can easily get a reproducible error. Also, a stub backend might help, so that there's no need to include an actual http call invocation.

**Comment by adamw** [comment] 2023-03-16 15:23
I'd like to have some code which I can copy-paste, run, and see the issue first-hand :)

**Comment by Allocer** [comment] 2023-03-16 16:24
Ok, so the code above is same, main app looks like:
```
object App extends ZIOAppDefault {

  val defaultCirceConfig = Configuration.default.withSnakeCaseMemberNames
  implicit val circeConfig: Configuration = defaultCirceConfig

  implicit val decoderError: Decoder[GeneralError] = deriveConfiguredDecoder
  implicit val decoderFirstErrorImpl: Decoder[FirstErrorImpl] = deriveConfiguredDecoder
  implicit val decoderSomeResponse: Decoder[SomeResponse] = deriveConfiguredDecoder

  implicit val testingBackend = HttpClientZioBackend.stub
    .whenRequestMatches(_ => true)
    .thenRespond(Response("""{"message": "error", "code": 65}""".trim, StatusCode.InternalServerError, "Something went wrong"))


  val client = ZIO.service[SttpBackend[Task, Any]].provide(HttpClientZioBackend.layer()).flatMap { backend =>
    basicRequest
      .get(uri"http://example.org")
      .response(asJsonEither[FirstErrorImpl, SomeResponse])
      .send(testingBackend)
      .map(_.body.left.map {
        case HttpError(body, statusCode) => FirstErrorImpl(body.message, statusCode.code)
        case DeserializationException(_, _) => SecondErrorImpl("serialization exception", 500)
      })
      .flatMap(ZIO.fromEither(_))
      .tap(response => ZIO.logInfo(response.toString))
  }

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = client
}
```
for this output I got `FirstErrorImpl` correctly mapped (see debugger). 

Now I changed to `trait`:
```
object App extends ZIOAppDefault {

  val defaultCirceConfig = Configuration.default.withSnakeCaseMemberNames
  implicit val circeConfig: Configuration = defaultCirceConfig

  implicit val decoderError: Decoder[GeneralError] = deriveConfiguredDecoder
  implicit val decoderFirstErrorImpl: Decoder[FirstErrorImpl] = deriveConfiguredDecoder
  implicit val decoderSomeResponse: Decoder[SomeResponse] = deriveConfiguredDecoder

  implicit val testingBackend = HttpClientZioBackend.stub
    .whenRequestMatches(_ => true)
    .thenRespond(Response("""{"message": "error", "code": 65}""".trim, StatusCode.InternalServerError, "Something went wrong"))


  val client = ZIO.service[SttpBackend[Task, Any]].provide(HttpClientZioBackend.layer()).flatMap { backend =>
    basicRequest
      .get(uri"http://example.org")
      .response(asJsonEither[GeneralError, SomeResponse])
      .send(testingBackend)
      .map(_.body.left.map {
        case HttpError(body, statusCode) => FirstErrorImpl(body.message, statusCode.code)
        case DeserializationException(_, _) => SecondErrorImpl("serialization exception", 500)
      })
      .flatMap(ZIO.fromEither(_))
      .tap(response => ZIO.logInfo(response.toString))
  }

  override def run: ZIO[Any with ZIOAppArgs with Scope, Any, Any] = client
}
```

And got Deserialization exception `sttp.client3.DeserializationException: DecodingFailure at : JSON decoding to CNil should never happen`

**Comment by adamw** [comment] 2023-03-17 12:50
I think the problem is in the circe decoder configuration:

```scala
import io.circe.generic.extras.Configuration
import io.circe.generic.extras.semiauto.deriveConfiguredDecoder
import io.circe.{Decoder, parser}

sealed trait GeneralError extends Throwable {
  def message: String
  def code: Int
}

object Errors {

  final case class FirstErrorImpl(message: String,  code: Int) extends GeneralError {
    override def getMessage: String = "error"
  }

  final case class SecondErrorImpl(message: String,  code: Int) extends GeneralError {
    override def getMessage: String = "error"
  }
}

object X extends App {

  val defaultCirceConfig = Configuration.default.withSnakeCaseMemberNames
  implicit val circeConfig: Configuration = defaultCirceConfig

  implicit val decoderError: Decoder[GeneralError] = deriveConfiguredDecoder

  val json = parser.parse("""{"message": "error", "code": 65}""").toOption.get
  println(json)
  println(decoderError.decodeJson(json))
}
```

gives `Left(DecodingFailure(CNil, List()))`, instead of the parsed instance.

**Comment by adamw** [comment] 2023-03-17 13:21
Not sure why `deriveConfiguredDecoder` doesn't work, but the following does:

```
  implicit val decoderError: Decoder[GeneralError] = List[Decoder[GeneralError]](
    deriveDecoder[FirstErrorImpl].widen,
    deriveDecoder[SecondErrorImpl].widen
  ).reduceLeft(_ or _)
```

**Comment by adamw** [comment] 2023-03-17 13:21
(following https://circe.github.io/circe/codecs/adt.html)

**Comment by adamw** [comment] 2023-03-17 13:25
Ah, that's probably because the default circe strategy for dealing with ADTs is to use a wrapper object, specifying the subclass. This is visible if you try to encode:

```
println(deriveEncoder[GeneralError].apply(FirstErrorImpl("error", 65)))

/*
{
  "FirstErrorImpl" : {
    "message" : "error",
    "code" : 65
  }
}
*/
```

I think if you want to use a "flat" strategy you'll need to manually combine the decoders for individual subclasses using `or`, as I've pasted above.

Maye this will help as well: https://edward-huang.com/circe/2020/07/21/parsing-json-with-circe-beyond-the-basics/

**Closed by adamw** 2023-03-17 13:25 UTC

**Comment by Allocer** [comment] 2023-03-17 19:04
> implicit val decoderError: Decoder[GeneralError] = List[Decoder[GeneralError]](
>     deriveDecoder[FirstErrorImpl].widen,
>     deriveDecoder[SecondErrorImpl].widen
>   ).reduceLeft(_ or _)

Thank you. I wouldn't have thought of it. It looks weird, but works ;).

**Comment by adamw** [comment] 2023-03-17 19:43
It's a strategy where you try to decode the incoming JSON using the provided decoders, picking the first one that doesn't fail. On the other hand, the circe-default one expects a hint (a discriminator) to be present, so that the "right" decoder can be picked upfront.
