### ISSUE TITLE
AsyncHttpClientFs2BackEnd refusing to close?

### ISSUE THREAD

**Issue by sergiojoker11** [softwaremill/sttp#1297] opened 2022-02-03 10:37 UTC
In the main class of my service I am using `AsyncHttpClientFs2Backend.resource[IO]()` and something is preventing graceful shutdown. The message I am getting is:
```
Non-daemon threads currently preventing JVM termination: - 32: Thread[DestroyJavaVM,5,main]
 -  - 28: Thread[AsyncHttpClient-3-1,5,main]
```

Presumably the AsyncHttpClient thread pool created  the thread that appears in the error. Maybe it is just a red herring?

Library version:`"com.softwaremill.sttp.client3" %% "async-http-client-backend-fs2" % "3.3.16"`

**Comment by Pask423** [comment] 2022-02-27 20:41
1. Could you try with newest version - `3.5.0` ?
2. Could you provide some minimal code snippet to reproduce error ?

**Comment by sergiojoker11** [comment] 2022-02-28 18:39
I'll start by answering 2).
2) Strangely enough, I have only been able to reproduce it on a k8s enviroment. The service using sttp library is executed as part of a daily k8s cron job overnight and every other morning I have to kill the job manually because it would not complete. The expectation is the job finishes in about 90 mins. On sbt I have tried about 50 times and it seems fine. 
The main program is basically an IOApp where `dependencies()` returns Resource[IO, (dep1, dep2, dep3)] and looks like the following:
```
def run(args: List[String]): IO[ExitCode] = {
    (for {
      _ <- dependencies().use { case (dep1, dep2, dep3) => 
        IO.delay(<somefun>)...
        }
      _ <- logger.info("Exiting")
    } yield ExitCode.Success).onError(err =>
      logger.error(s"Loader stopped execution unexpectedly. Error: ${err.getLocalizedMessage}"))
  }
```
I do always see "Exiting" and then the above error. So, I can't really provide reproduction steps... sorry! I wish I had them.
Scala version 2.12.14. Sbt version 1.5.5. JVM used on k8s environment version 11.

1) considering the answer for 2) I cannot answer 1)

**Comment by Pask423** [comment] 2022-02-28 19:18
Regarding relevant changes it's hard to say `3.1.16` was release like year ago.

**Comment by Pask423** [comment] 2022-02-28 19:30
After quick look up maybe you are facing similar root cause for problem as here for `OkHttp`  https://github.com/kubernetes-client/java/issues/865

**Comment by Pask423** [comment] 2022-03-01 19:47
I think that it is more `AsyncHttpClient` and `k8s` related issues as it is impossible to recreated when run from `sbt`

**Comment by Pask423** [comment] 2022-04-11 08:21
Impossible to recreate from pure `sttp`, closing

**Closed by Pask423** 2022-04-11 08:21 UTC
